/**
 * Maps legacy snake_case icon ids (Material-style) to @ant-design/icons components.
 * Unknown names fall back to QuestionCircleOutlined.
 */
import {
  ApiOutlined,
  AppstoreAddOutlined,
  AppstoreOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  BankOutlined,
  BarChartOutlined,
  BellFilled,
  BellOutlined,
  BoldOutlined,
  BookFilled,
  BookOutlined,
  BorderOutlined,
  BranchesOutlined,
  BugOutlined,
  BulbOutlined,
  CalendarOutlined,
  CarryOutFilled,
  CarryOutOutlined,
  CheckCircleFilled,
  CheckCircleOutlined,
  CheckOutlined,
  ClockCircleOutlined,
  CloseCircleOutlined,
  CloseOutlined,
  CloudOutlined,
  CoffeeOutlined,
  CommentOutlined,
  CompassFilled,
  CompassOutlined,
  CopyrightOutlined,
  CreditCardOutlined,
  CrownFilled,
  CrownOutlined,
  DashboardFilled,
  DashboardOutlined,
  DatabaseOutlined,
  DeleteOutlined,
  DesktopOutlined,
  DisconnectOutlined,
  DollarOutlined,
  DownOutlined,
  DragOutlined,
  EditOutlined,
  EllipsisOutlined,
  EnvironmentOutlined,
  ExperimentOutlined,
  ExportOutlined,
  EyeInvisibleOutlined,
  EyeOutlined,
  FileAddOutlined,
  FileTextOutlined,
  FilterOutlined,
  FireFilled,
  FireOutlined,
  FontSizeOutlined,
  FormOutlined,
  FormatPainterOutlined,
  GiftFilled,
  GiftOutlined,
  GlobalOutlined,
  GoldOutlined,
  GoogleOutlined,
  HeartFilled,
  HeartOutlined,
  HistoryOutlined,
  HomeFilled,
  HomeOutlined,
  ImportOutlined,
  InboxOutlined,
  InfoCircleOutlined,
  ItalicOutlined,
  LikeFilled,
  LikeOutlined,
  LineChartOutlined,
  LinkOutlined,
  LockOutlined,
  LogoutOutlined,
  MailOutlined,
  MenuOutlined,
  MessageOutlined,
  MobileOutlined,
  MoreOutlined,
  NotificationFilled,
  NotificationOutlined,
  OrderedListOutlined,
  PayCircleFilled,
  PayCircleOutlined,
  PercentageOutlined,
  PieChartOutlined,
  PlayCircleOutlined,
  PlusCircleOutlined,
  PlusOutlined,
  PushpinOutlined,
  QuestionCircleOutlined,
  ReadFilled,
  ReadOutlined,
  RedoOutlined,
  RiseOutlined,
  RocketFilled,
  RocketOutlined,
  SafetyCertificateFilled,
  SafetyCertificateOutlined,
  SafetyOutlined,
  SaveOutlined,
  ScheduleFilled,
  ScheduleOutlined,
  SearchOutlined,
  SecurityScanOutlined,
  SendOutlined,
  SettingFilled,
  SettingOutlined,
  ShareAltOutlined,
  ShopFilled,
  ShopOutlined,
  SmileFilled,
  SmileOutlined,
  StarFilled,
  StarOutlined,
  StopOutlined,
  SwapOutlined,
  TabletOutlined,
  TeamOutlined,
  ThunderboltFilled,
  ThunderboltOutlined,
  ToolOutlined,
  TrophyFilled,
  TrophyOutlined,
  UndoOutlined,
  UnlockOutlined,
  UnorderedListOutlined,
  UploadOutlined,
  UserAddOutlined,
  UserOutlined,
  UserSwitchOutlined,
  WalletOutlined,
  WarningOutlined,
} from "@ant-design/icons";

const FALLBACK = QuestionCircleOutlined;

/** @type {Record<string, string>} */
const ALIASES = {
  book: "menu_book",
  card_giftcard: "redeem",
  groups: "group",
  poll: "how_to_vote",
  remove_circle: "cancel",
  report_problem: "report",
};

/**
 * @typedef {import('react').ComponentType<{ className?: string; style?: import('react').CSSProperties }>} IconComp
 */

/** @type {Record<string, IconComp | { o: IconComp; f?: IconComp }>} */
const GLYPH = {
  account_balance_wallet: WalletOutlined,
  account_circle: UserOutlined,
  account_tree: BranchesOutlined,
  add: PlusOutlined,
  add_circle: PlusCircleOutlined,
  add_notes: FileAddOutlined,
  admin_panel_settings: SettingOutlined,
  analytics: LineChartOutlined,
  app_shortcut: AppstoreAddOutlined,
  appstore: AppstoreOutlined,
  arrow_back: ArrowLeftOutlined,
  arrow_forward: ArrowRightOutlined,
  article: FileTextOutlined,
  assignment: CarryOutOutlined,
  auto_awesome: RocketOutlined,
  auto_graph: LineChartOutlined,
  auto_stories: { o: ReadOutlined, f: ReadFilled },
  bar_chart: BarChartOutlined,
  bolt: { o: ThunderboltOutlined, f: ThunderboltFilled },
  bookmark_add: FileAddOutlined,
  calendar_month: CalendarOutlined,
  cancel: CloseCircleOutlined,
  castle: BankOutlined,
  celebration: GiftOutlined,
  chat: MessageOutlined,
  chat_bubble: CommentOutlined,
  check: CheckOutlined,
  check_circle: { o: CheckCircleOutlined, f: CheckCircleFilled },
  chevron_left: ArrowLeftOutlined,
  chevron_right: ArrowRightOutlined,
  circle: BorderOutlined,
  close: CloseOutlined,
  cloud_off: DisconnectOutlined,
  coffee: CoffeeOutlined,
  construction: ToolOutlined,
  copyright: CopyrightOutlined,
  credit_card: CreditCardOutlined,
  currency_bitcoin: ApiOutlined,
  dashboard: { o: DashboardOutlined, f: DashboardFilled },
  database: DatabaseOutlined,
  delete_sweep: DeleteOutlined,
  description: FileTextOutlined,
  desktop_windows: DesktopOutlined,
  diamond: GoldOutlined,
  download_for_offline: ImportOutlined,
  drag_indicator: DragOutlined,
  edit: EditOutlined,
  edit_document: FileTextOutlined,
  edit_note: FormOutlined,
  edit_square: FormOutlined,
  emoji_events: TrophyOutlined,
  error: CloseCircleOutlined,
  event_available: ClockCircleOutlined,
  event: ClockCircleOutlined,
  expand_less: ArrowDownOutlined,
  expand_more: DownOutlined,
  explore: { o: CompassOutlined, f: CompassFilled },
  favorite: { o: HeartOutlined, f: HeartFilled },
  filter_1: FilterOutlined,
  flag: EnvironmentOutlined,
  format_bold: BoldOutlined,
  format_italic: ItalicOutlined,
  format_list_bulleted: UnorderedListOutlined,
  format_list_numbered: OrderedListOutlined,
  format_paint: FormatPainterOutlined,
  format_quote: CommentOutlined,
  format_size: FontSizeOutlined,
  forum: CommentOutlined,
  gavel: SecurityScanOutlined,
  gift: GiftOutlined,
  google: GoogleOutlined,
  grade: { o: StarOutlined, f: StarFilled },
  group: TeamOutlined,
  help: QuestionCircleOutlined,
  help_outline: QuestionCircleOutlined,
  history: HistoryOutlined,
  history_edu: ReadOutlined,
  home: { o: HomeOutlined, f: HomeFilled },
  how_to_vote: PieChartOutlined,
  info: InfoCircleOutlined,
  inventory_2: InboxOutlined,
  leaderboard: RiseOutlined,
  library_books: BookOutlined,
  lightbulb: BulbOutlined,
  link: LinkOutlined,
  local_atm: BankOutlined,
  local_fire_department: { o: FireOutlined, f: FireFilled },
  lock: LockOutlined,
  lock_open: UnlockOutlined,
  logout: LogoutOutlined,
  mail: MailOutlined,
  mark_email_read: MailOutlined,
  menu_book: BookOutlined,
  military_tech: SafetyCertificateOutlined,
  more_horiz: EllipsisOutlined,
  more_vert: MoreOutlined,
  north_east: RiseOutlined,
  notification_important: WarningOutlined,
  notifications: BellOutlined,
  notifications_active: { o: BellOutlined, f: BellFilled },
  open_in_new: ExportOutlined,
  payments: PayCircleOutlined,
  pending: ClockCircleOutlined,
  percent: PercentageOutlined,
  person: UserOutlined,
  person_add: UserAddOutlined,
  pin: PushpinOutlined,
  play_arrow: PlayCircleOutlined,
  priority_high: StopOutlined,
  psychology: ExperimentOutlined,
  public: GlobalOutlined,
  publish: UploadOutlined,
  radio_button_checked: CheckCircleOutlined,
  rate_review: CommentOutlined,
  redeem: { o: GiftOutlined, f: GiftFilled },
  redo: RedoOutlined,
  remove: CloseOutlined,
  reorder: SwapOutlined,
  report: WarningOutlined,
  rocket_launch: { o: RocketOutlined, f: RocketFilled },
  savings: SaveOutlined,
  schedule: { o: ScheduleOutlined, f: ScheduleFilled },
  search: SearchOutlined,
  security: SafetyOutlined,
  send: SendOutlined,
  sentiment_satisfied: SmileOutlined,
  sentiment_very_satisfied: { o: SmileOutlined, f: SmileFilled },
  settings: { o: SettingOutlined, f: SettingFilled },
  share: ShareAltOutlined,
  shield: { o: SafetyCertificateOutlined, f: SafetyCertificateFilled },
  shield_lock: LockOutlined,
  shopping_bag: ShopOutlined,
  skull: BugOutlined,
  smartphone: MobileOutlined,
  sms: MessageOutlined,
  social_leaderboard: TrophyOutlined,
  south_west: ArrowDownOutlined,
  space_dashboard: DashboardOutlined,
  star: { o: StarOutlined, f: StarFilled },
  stars: StarFilled,
  storefront: { o: ShopOutlined, f: ShopFilled },
  storm: CloudOutlined,
  switch_account: UserSwitchOutlined,
  tablet_mac: TabletOutlined,
  text_fields: FontSizeOutlined,
  thumb_up: LikeOutlined,
  title: FontSizeOutlined,
  toll: DollarOutlined,
  trending_up: RiseOutlined,
  travel_explore: CompassOutlined,
  trophy: { o: TrophyOutlined, f: TrophyFilled },
  undo: UndoOutlined,
  verified: SafetyCertificateOutlined,
  verified_user: SafetyCertificateOutlined,
  visibility: EyeOutlined,
  visibility_off: EyeInvisibleOutlined,
  warning: WarningOutlined,
  workspace_premium: { o: CrownOutlined, f: CrownFilled },
  campaign: NotificationOutlined,
};

/**
 * @param {string | undefined | null} snakeName
 * @param {boolean} filled
 * @returns {IconComp}
 */
export function resolveSnakeCaseAntIcon(snakeName, filled) {
  const raw = String(snakeName ?? "").trim();
  if (!raw) {
    return FALLBACK;
  }
  const key = ALIASES[raw] ?? raw;
  const glyph = GLYPH[key];
  if (!glyph) {
    return FALLBACK;
  }
  if (typeof glyph === "function") {
    return glyph;
  }
  if (filled && glyph.f) {
    return glyph.f;
  }
  return glyph.o;
}
