import { defineConfig, loadEnv } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), "");
  const backendOrigin = env.VITE_BACKEND_ORIGIN || "http://localhost:4000";

  return {
    plugins: [
      react(),
      VitePWA({
        registerType: "autoUpdate",
        includeAssets: ["Logo.svg", "icon-192.png", "icon-512.png", "icon-180.png", "favicon-32.png", "robots.txt"],
        manifest: {
          name: "TaleStead",
          short_name: "TaleStead",
          description: "Read, write, and share stories on TaleStead.",
          start_url: "/dashboard",
          display: "standalone",
          background_color: "#020617",
          theme_color: "#f97316",
          icons: [
            { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
            { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
            { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
          ],
        },
        workbox: {
          navigateFallback: "/index.html",
          runtimeCaching: [
            {
              // Static assets generated by Vite
              urlPattern: ({ request }) =>
                request.destination === "style" ||
                request.destination === "script" ||
                request.destination === "font" ||
                request.destination === "image",
              handler: "StaleWhileRevalidate",
              options: {
                cacheName: "talestead-static-assets",
                expiration: {
                  maxEntries: 200,
                  maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
                },
              },
            },
            {
              // Reader APIs for dashboard, home, rankings, lists, etc.
              urlPattern: ({ url }) => url.pathname.startsWith("/reader/") || url.pathname === "/reader/dashboard",
              handler: "NetworkFirst",
              options: {
                cacheName: "talestead-reader-api",
                networkTimeoutSeconds: 5,
                expiration: {
                  maxEntries: 200,
                  maxAgeSeconds: 60 * 60 * 24 * 7, // 7 days
                },
              },
            },
            {
              // Story chapters for offline reading
              urlPattern: ({ url }) =>
                url.pathname.includes("/reader/stories/") && url.pathname.includes("/chapters/"),
              handler: "NetworkFirst",
              options: {
                cacheName: "talestead-chapters",
                networkTimeoutSeconds: 5,
                expiration: {
                  maxEntries: 200,
                  maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
                },
              },
            },
          ],
        },
      }),
    ],
    server: {
      host: true,
      proxy: {
        "/api": {
          changeOrigin: true,
          rewrite: (path) => path.replace(/^\/api/, ""),
          target: backendOrigin,
        },
      },
    },
    preview: {
      port: 4173,
      host: true,
      proxy: {
        "/api": {
          changeOrigin: true,
          rewrite: (path) => path.replace(/^\/api/, ""),
          target: backendOrigin,
        },
      },
    },
  };
});
